name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:


permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.release-please.outputs['nipaw_core--release_created'] }}
      node: ${{ steps.release-please.outputs['nipaw_node--release_created'] }}
      node_tag_name: ${{ steps.release-please.outputs['nipaw_node--tag_name'] }}
      github: ${{ steps.release-please.outputs['nipaw_github--release_created'] }}
      gitee: ${{ steps.release-please.outputs['nipaw_gitee--release_created'] }}
      gitcode: ${{ steps.release-please.outputs['nipaw_gitcode--release_created'] }}
      cnb: ${{ steps.release-please.outputs['nipaw_cnb--release_created'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json


  publish-lib:
    runs-on: ubuntu-latest
    needs: [ release ]
    if: ${{ needs.release.outputs.github || needs.release.outputs.gitcode || needs.release.outputs.gitee || needs.release.outputs.cnb }}
    steps:
      - name: 检出代码
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 Rust 工具链
        uses: dtolnay/rust-toolchain@stable

      - name: 设置 Rust 缓存
        uses: swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1

      - name: 发布nipaw_core
        if: needs.release.outputs.core
        run: |
          cargo publish --package nipaw_core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布nipaw_github
        if: needs.release.outputs.github
        run: |
          cargo publish --package nipaw_github
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布nipaw_gitcode
        if: needs.release.outputs.gitcode
        run: |
          cargo publish --package nipaw_gitcode
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布nipaw_gitee
        if: needs.release.outputs.gitee
        run: |
          cargo publish --package nipaw_gitee
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

      - name: 发布nipaw_cnb
        if: needs.release.outputs.cnb
        run: |
          cargo publish --package nipaw_cnb
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}


  build:
    needs: release
    if: needs.release.outputs.node
    uses: ./.github/workflows/build.yml

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ release, build ]
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 下载npm包
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: "npm-package"
          path: nipaw_node

      - name: 下载构建产物
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          pattern: nipaw-node*
          path: nipaw_node/artifacts

      - name: 设置pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.22.0

      - name: 发布npm包
        run: |
          pnpm install
          pnpm config set provenance true
          pnpm config set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm run create-npm-dirs
          pnpm run artifacts
          pnpm publish --access public
        working-directory: nipaw_node
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 上传Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            nipaw_node/artifacts/nipaw-node-*/nipaw*.node
          tag_name: ${{ needs.release.outputs.node_tag_name }}

